compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: 0

logFilters:
  - code: YN0004
    level: discard

nodeLinker: node-modules

plugins:
  - checksum: 026e73679828ee4858db990ba2c3bf75db99d3cbe7c17386a595ede2d01f6bff43b344a285d944de310513e9d16c8fcb55ff6bd368b063adafb19e59f767d158
    path: .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
    spec: "https://raw.githubusercontent.com/LavaMoat/LavaMoat/main/packages/yarn-plugin-allow-scripts/bundles/@yarnpkg/plugin-allow-scripts.js"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
