version: 2.1

executors:
  node-browsers:
    docker:
      - image: cimg/node:18.20-browsers

workflows:
  storybook:
    jobs:
      - prep-deps
      - prep-build-storybook:
          requires:
            - prep-deps
      - job-announce-storybook:
          requires:
            - prep-build-storybook

jobs:
  prep-deps:
    executor: node-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install deps
          command: |
            yarn install
      - save_cache:
          key: dependency-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Postinstall
          command: |
            yarn setup
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  prep-build-storybook:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build:storybook
          command: yarn build-storybook
      - persist_to_workspace:
          root: .
          paths:
            - storybook-static

  job-announce-storybook:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - store_artifacts:
          path: storybook-static
          destination: storybook
      - run:
          name: build:announce
          command: ./.circleci/scripts/metamaskbot-build-announce.js
