version: 2.1

executors:
  node-browsers:
    docker:
      - image: circleci/node:14-browsers

workflows:
  storybook:
    jobs:
      - prep-deps
      - prep-build-storybook:
          requires:
            - prep-deps
      - job-announce-storybook:
          requires:
            - prep-build-storybook
      - job-publish-storybook:
          filters:
            branches:
              only: main
          requires:
            - prep-build-storybook

jobs:
  prep-deps:
    executor: node-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Install deps
          command: |
            yarn install
      - save_cache:
          key: dependency-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - run:
          name: Postinstall
          command: |
            yarn setup
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  prep-build-storybook:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: build:storybook
          command: yarn build-storybook
      - persist_to_workspace:
          root: .
          paths:
            - storybook-static

  job-announce-storybook:
    executor: node-browsers
    steps:
      - checkout
      - attach_workspace:
          at: .
      - store_artifacts:
          path: storybook-static
          destination: storybook
      - run:
          name: build:announce
          command: ./.circleci/scripts/metamaskbot-build-announce.js

  job-publish-storybook:
    executor: node-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - '3d:49:29:f4:b2:e8:ea:af:d1:32:eb:2a:fc:15:85:d8'
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: storybook:deploy
          command: |
            git remote add storybook git@github.com:MetaMask/metamask-storybook.git
            yarn storybook:deploy
